name: Online-Botique CI pipeline

on:
 push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker image
        run: docker build -f src/frontend/Dockerfile -t microservices-demo/frontend:latest src/frontend
  
      # - name: Display Repository Structure
      #   run: |
      #       pwd
      #       ls -la
      